name: Build and Push Container Image

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - frontend/**
#       - backend/**
#       - docker-compose.yaml
#   workflow_dispatch:
on: 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bypass Cloudflare for GitHub Action
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v1.1.1
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.naulak.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Build Docker images
        run: docker compose build --no-cache
      - name: Push Docker images
        run: docker compose push